### ISSUE TITLE
502() No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by kvreem** [serverless/serverless-graphql#260]
My application works locally but when it comes time to deploy I get the following issue in the Chrome developer console. 

`Failed to load https://XXXXX.execute-api.us-west-1.amazonaws.com/production/graphql: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://XXX.XXX' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

My deployment bucket is pointing to my domain, and I created a certificate and distribution to have enable HTTPS. 

In my `handler.js` I have the following code and added  `output.headers['Access-Control-Allow-Credentials'] = 'true';` because from my research this is required to work with HTTPS. 

```
exports.graphqlHandler = function graphqlHandler(event, context, callback) {
    function callbackFilter(error, output) {
        // eslint-disable-next-line no-param-reassign
        output.headers['Access-Control-Allow-Origin'] = '*';
        output.headers['Access-Control-Allow-Credentials'] = 'true';
        callback(error, output);
    }
```

My YAML looks like this for my `app-backend` 

```
functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
  api:
    handler: handler.apiHandler
    events:
    - http:
        path: api
        method: get
        cors: true


```
And just for sanity's sake this is where I am initializing my Apollo client i replace http://localhost:4000

`const networkInterface = createNetworkInterface({ uri: 'https://XXX.execute-api.us-west-1.amazonaws.com/production/graphql' });`
